In [1]:
import numpy as np

In [2]:
liste = [2, 3, 1, 4, 6]

array = np.array(liste)

In [3]:
print(liste, type(liste))

print(liste[0])
print(liste[-1])
print(liste[1:3])

[2, 3, 1, 4, 6] <class 'list'>
2
6
[3, 1]


In [4]:
print(array, type(array))

print(array[0])
print(array[-1])
print(array[1:3])

[2 3 1 4 6] <class 'numpy.ndarray'>
2
6
[3 1]


In [5]:
A = np.array([[1, 2], [3, 4]])

print(A, type(A))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [6]:
print(A[:, 0])
print(A[0, :])

[1 3]
[1 2]


In [7]:
v = np.array([i for i in range(12)])
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
print(v[1])
print(v[-1])

1
11


In [9]:
# Lösung
print(v[::2]) # Jedes zweite Element
print(v[::-1]) # Rückwärts
print(v[3:8:2]) # 4., 6. und 8. Element

[ 0  2  4  6  8 10]
[11 10  9  8  7  6  5  4  3  2  1  0]
[3 5 7]


In [10]:
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
print(B[1, :])
print(B[1, 1])

[5 6 7 8]
6


In [12]:
# Lösung
print(B[::2]) # Jede zweite Zeile
print(B[:,1:4:2]) # 2. und 4. Spalte

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [13]:
w = np.arange(1, 6)
w

array([1, 2, 3, 4, 5])

In [14]:
print(np.mean(w))
print(np.sum(w))
print(np.min(w))
print(np.max(w))
print(np.std(w))

3.0
15
1
5
1.4142135623730951


In [15]:
# Lösung:

def summary_statistics(x: np.ndarray) -> None:
    """Prints summary results for input array"""
    print_statistic = lambda s: print(f"{s.__name__}: {s(x)}")
    for s in [np.mean, np.sum, np.min, np.max, np.std]:
        print_statistic(s)

In [22]:
print(w)
summary_statistics(w)

[1 2 3 4 5]
mean: 3.0
sum: 15
amin: 1
amax: 5
std: 1.4142135623730951


In [21]:
print(A)
summary_statistics(A)

[[1 2]
 [3 4]]
mean: 2.5
sum: 10
amin: 1
amax: 4
std: 1.118033988749895


In [26]:
print(np.sum(A)) # alle Einträge
print(np.sum(A, axis = 0)) # Summe jeder Spalte
print(np.sum(A, axis = 1)) # Summe jeder Zeile

10
[4 6]
[3 7]


In [17]:
print(np.exp(w))
print(np.log(w))
print(np.sin(w))
print(np.cos(w))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [33]:
print(np.exp(A), "\n")
print(np.log(A), "\n")
print(np.sin(A), "\n")
print(np.cos(A))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]] 

[[0.         0.69314718]
 [1.09861229 1.38629436]] 

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]] 

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]


In [18]:
print(w + 1)
print(w - 1)
print(w / 2)
print(w * 2)
print(w ** 2)

[2 3 4 5 6]
[0 1 2 3 4]
[0.5 1.  1.5 2.  2.5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [34]:
print(A + 1, "\n")
print(A - 1, "\n")
print(A / 2, "\n")
print(A * 2, "\n")
print(A ** 2)

[[2 3]
 [4 5]] 

[[0 1]
 [2 3]] 

[[0.5 1. ]
 [1.5 2. ]] 

[[2 4]
 [6 8]] 

[[ 1  4]
 [ 9 16]]
