In [1]:
import numpy as np

In [2]:
liste = [2, 3, 1, 4, 6]

array = np.array(liste)

In [22]:
print(liste, type(liste))

print(liste[0])
print(liste[-1])
print(liste[1:3])

[2, 3, 1, 4, 6] <class 'list'>
2
6
[3, 1]


In [23]:
print(array, type(array))

print(array[0])
print(array[-1])
print(array[1:3])

[2 3 1 4 6] <class 'numpy.ndarray'>
2
6
[3 1]


In [29]:
A = np.array([[1, 2], [3, 4]])

print(A, type(A))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [30]:
print(A[:, 0])
print(A[0, :])

[1 3]
[1 2]


In [34]:
v = np.array([i for i in range(12)])
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
# Lösung
print(v[::2]) # Jedes zweite Element
print(v[::-1]) # Rückwärts
print(v[3:8:2]) # 4., 6. und 8. Element

[ 0  2  4  6  8 10]
[11 10  9  8  7  6  5  4  3  2  1  0]
[3 5 7]


In [62]:
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
# Lösung
print(B[::2]) # Jede zweite Zeile
print(B[:,1:4:2]) # 2. und 4. Spalte

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
